### ISSUE TITLE
wc might be an empty string

### ISSUE THREAD

**Issue by choldrim** [jquast/wcwidth#24] opened 2018-02-08 07:44 UTC
https://github.com/jquast/wcwidth/blob/c71459ea91af86f3bbcdac2c8ed5e7773da2d848/wcwidth/wcwidth.py#L104-L182

if `wc` is an empty string, an `TypeError: ord() expected a character...` exception will be raised

if there would be a statement `if len(wc) == 0: return 0` before `ord(wc)`, it will be better, I think.

**Comment by serhiy-storchaka** [comment] 2020-12-13 20:09
From docstring: "Given one unicode character, ...".

Empty string is not one unicode character. You pass value which does satisfy function contract and get an error. Similar error you will get when pass an unicode string containing more than one character.

**Comment by jquast** [comment] 2020-12-20 13:03
I agree and thanks for the report I will work on this as soon as I am able

**Comment by wjandrea** [comment] 2021-08-14 20:08
@serhiy-storchaka, The problem is that there should be a specific error about it. For example, it could be as simple as subbing out `ord` for `wcwidth` in that error:
```python
if len(wc) != 1:
    msg = 'wcwidth() expected a character, but string of length {} found'.format(len(wc))
    raise TypeError(msg)
ucs = ord(wc)
```

Example run:
```python
>>> wcwidth('')
Traceback (most recent call last):
  ...
TypeError: wcwidth() expected a character, but string of length 0 found
>>> wcwidth('ab')
Traceback (most recent call last):
  ...
TypeError: wcwidth() expected a character, but string of length 2 found
```

**Comment by jquast** [comment] 2023-10-30 19:54
This is fixed in today's release. On empty string, wcwidth returns 0. Thanks!

**Closed by jquast** 2023-10-30 19:54 UTC
Labels: bug
